version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sinon
    versions:
    - 9.2.2
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: mocha
    versions:
    - 8.2.1
  - dependency-name: chai
    versions:
    - 4.2.0
  - dependency-name: gulp-babel
    versions:
    - 6.1.3
